[package]
name = "bitcoin-rs-ext-blockfilterindex"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
description = "bitcoin-rs :: ext-blockfilterindex — BIP157/158 basic filter index extension"

[lints]
workspace = true

[dependencies]
bitcoin-rs-ext-api.workspace = true
bitcoin-rs-storage.workspace = true
bitcoin.workspace = true
thiserror.workspace = true

[dev-dependencies]
parking_lot.workspace = true
