[package]
name = "bitcoin-rs-ext-api"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
description = "bitcoin-rs :: ext-api — extension contract for node-side index consumers"

[lints]
workspace = true

[dependencies]
bitcoin-rs-primitives.workspace = true
serde.workspace = true

[dev-dependencies]
sonic-rs.workspace = true
